alphabet = ['\N{REGIONAL INDICATOR SYMBOL LETTER A}','\N{REGIONAL INDICATOR SYMBOL LETTER B}', 
        '\N{REGIONAL INDICATOR SYMBOL LETTER C}','\N{REGIONAL INDICATOR SYMBOL LETTER D}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER E}','\N{REGIONAL INDICATOR SYMBOL LETTER F}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER G}','\N{REGIONAL INDICATOR SYMBOL LETTER H}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER I}','\N{REGIONAL INDICATOR SYMBOL LETTER J}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER K}','\N{REGIONAL INDICATOR SYMBOL LETTER L}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER M}','\N{REGIONAL INDICATOR SYMBOL LETTER N}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER O}','\N{REGIONAL INDICATOR SYMBOL LETTER P}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER Q}','\N{REGIONAL INDICATOR SYMBOL LETTER R}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER S}','\N{REGIONAL INDICATOR SYMBOL LETTER T}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER U}','\N{REGIONAL INDICATOR SYMBOL LETTER V}', 
        '\N{REGIONAL INDICATOR SYMBOL LETTER W}','\N{REGIONAL INDICATOR SYMBOL LETTER X}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER Y}','\N{REGIONAL INDICATOR SYMBOL LETTER Z}']   

emoji = ["🕵🏼", "✅"]


Mots=[["Rivière","Océan","Fleuve","Ruisseau","Mer"],
["KFC","McDonalds","Burger King","Quick","Subway","Pizza Hut"],
["Douche","Baignoire", "Piscine"],
["Papillon","Abeille","Sauterelle","Mille-pattes"],
["Twitter","Instagram", "Facebook", "Pinterest", "Snapchat","TikTok"],
["Star Wars","Le Seigneur des Anneaux", "Harry Potter"],
["Neige","Pluie","Vent","Nuage","Brouillard"],
["Naruto","Sasuke","Sakura","Kakashi"],
["Piano","Violon","Xylophone","Trompette"],
["Samsung","Nokia","Apple", "OnePlus", "Huawei"],
["Ninho","Booba","Nekfeu","Orelsan"],
["Nike","Adidas","Puma","Asics"],
["Orange","Pomme", "Poire", "Kiwi"],
["Mars","Twix","Bounty", "Lion", "Kinder Country","Kit Kat", "Snickers","Kinder Bueno"],
["Handball","Basketball","Football", "Rugby", "Volleyball", "Badminton", "Tennis"],
["Pelle","Râteau","Pioche","Hache"],
["Brioche","Pain","Croissant", "Chocolatine"],
["Cheval","Âne", "Vache", "Coq","Lapin"],
["Dauphin", "Baleine", "Orque", "Requin", "Thon", "Saumon"],
["Avion","Fusée", "Hélicoptère", "Voiture", "Train"],
["Casquette","Bonnet","Béret"],
["Orange","Citron","Pamplemousse"],
["Youtube", "Twitch", "Dailymotion"],
["Café","Thé", "Jus", "Lait"],
["Coca-Cola", "Fanta", "Pepsi", "Oasis", "Ice Tea", "Schweppes"],
["Ébola", "Sida", "Coronavirus", "Peste", "Grippe"],
["PS4","Xbox One", "Switch", "Wii", "Gamecube"],
["Patron","Stagiaire", "Secrétaire", "Cadre"],
["Son Goku","Vegeta", "Broly", "Son Gohan"],
["Mario", "Luigi","Zelda"],
["Roth","Tocqueville", "Aristophane", "Nietzsche"],
["Fondue","Raclette", "Tartiflette"],
["Netflix", "Disney+", "Amazon Prime Video"],
["Einstein","Newton","Galilée","Hawking","Darwin","Marie Curie"],
["Neymar","Messi","Ronaldo","Zidane","Mbappé","Pogba","Ibrahimović"],
["Daenerys","Jon Snow","Arya Stark","Cersei Lannister","Tyrion Lannister", "Sansa Stark"],
["Crêpes","Gaufre","Madeleine","Cookie","Muffin"],
["David Guetta","Martin Garrix","Avicii","Alan Walker","Kygo","Marshmellow"],
["Cyprien","Norman","Squeezie","Le Rire Jaune","Amixem","McFly et Carlito"],
["Hitler","Staline","Mao","Lenine","Fidel Castro","Saddam Hussein","Mussolini"],
["Emmanuel Macron", "Nicolas Sarkozy","Jacques Chirac","François Hollande"],
["Carpe","Truite","Saumon","Cabillaud","Brochet","Anguille"],
["Échecs","Dames","Poker","Tarot","Belote"],
["Étoile","Lune","Soleil","Planètes"],
["Vin","Champagne","Bière","Whisky","Vodka"],
["Tigre","Guépard","Lynx","Puma","Ocelot"],
["Christianisme","Judaïsme","Islam","Bouddhisme","Hindouisme"],
["Fifa","Call of Duty","PES","GTA"],
["Sudoku","Mots croisés","Mastermind","Rubik's Cube"],
["The Beatles","Queen","ABBA","The Eagles","The Rolling Stones","AC/DC","Pink Floyd"],
["Nekfeu","Vald","PNL","Ninho","Lorenzo","Damso","Orelsan"],
["Tunisie","Maroc","Algérie","Lybie","Égypte"]


]